files:
  - source: '*.mdx'
    ignore:
      - Home.md
      - locales/*/*
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
  - source: messages/en.json
    translation: /messages/%two_letters_code%.json
